admins:
  - Kaustubh-pande
  - add-new1
repos:
  TEST-WORKFLOW:
    approvers:
      - Kaustubh-pande
      - new1
    reviewers:
      - Kaustubh-pande
      - bcz
  repo-b:
    reviewers:
      - pqr 
    approvers:
      - abcz
