admins:
  - Kaustubh-pande
repos:
  TEST-WORKFLOW:
    approvers:
      - Kaustubh-pande
      - n20
    reviewers:
      - Kaustubh-pande
      - bcz
  repo-b:
    reviewers:
      - rpancham 
    approvers:
      - test
