admins:
  - Kaustubh-pande
  - add-new
repos:
  TEST-WORKFLOW:
    approvers:
      - Kaustubh-pande
      - xyz
    reviewers:
      - Kaustubh-pande
      - this-is-working
  repo-b:
    reviewers:
      - pqr 
    approvers:
    
