admins:
  - Kaustubh-pande
  - add-new231
repos:
  TEST-WORKFLOW:
    approvers:
      - Kaustubh-pande
      - n5
    reviewers:
      - Kaustubh-pande
      - bcz
  repo-b:
    reviewers:
      - rpancham 
    approvers:
      - test
