name: Bulk Delete Branches Except Main

on:
  workflow_dispatch:  # Manual trigger

jobs:
  delete-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Delete all branches except main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG_NAME: Kaustubh-pande
          REPO_NAME: test-workflow
        run: |
          set -e
          ORG="$ORG_NAME"
          REPO="$REPO_NAME"
          TOKEN="$GITHUB_TOKEN"
          
          echo "Fetching branches for $ORG/$REPO"
          
          branches=$(curl -s -H "Authorization: token $TOKEN" \
            "https://api.github.com/repos/$ORG/$REPO/branches?per_page=100" | jq -r '.[].name')
          
          for branch in $branches; do
            if [ "$branch" != "main" ]; then
              echo "Deleting branch: $branch"
              curl -s -X DELETE -H "Authorization: token $TOKEN" \
                "https://api.github.com/repos/$ORG/$REPO/git/refs/heads/$branch"
            else
              echo "Skipping main branch"
            fi
          done
