name: Issue Command

on:
  issue_comment:
    types: [created]

jobs:
  lgtm:
    runs-on: ubuntu-latest
    steps:
      - name: Check for LGTM command
        if: github.event.comment.body == '/lgtm'
        run: |
          gh issue add-label ${{ github.event.issue.number }} lgtm
        env:
          GH_TOKEN: ${{ github.TOKEN }}
