name: Issue Command

on:
  issues:
    types:
      - reopened
      - opened

jobs:
  lgtm:
    runs-on: ubuntu-latest
    steps:
      - name: Check for LGTM command
        if: github.event.comment.body == '/lgtm'
        run: |
          gh issue edit ${{ github.event.issue.number }} --add-label lgtm
        env:
          GH_TOKEN: ${{ github.TOKEN }}
